models:
  - name: dim_customer
    description: "Customer dimension table capturing the latest customer attributes."
    columns:
      - name: customer_id
        description: "Unique customer identifier."
        tests:
          - not_null
          - unique
      - name: customer_unique_id
        tests:
          - not_null
      - name: customer_zip_code_prefix
        tests:
          - not_null
      - name: customer_city
        tests:
          - not_null
      - name: customer_state
        tests:
          - not_null         

  - name: dim_seller
    description: "Seller dimension table capturing the latest seller attributes."
    columns:
      - name: seller_id
        tests:
          - not_null
          - unique
      - name: seller_zip_code_prefix
        tests:
          - not_null
      - name: seller_city
        tests:
          - not_null
      - name: seller_state
        tests:
          - not_null

  - name: dim_product
    description: "Product dimension table containing product details."
    columns:
      - name: product_id
        tests:
          - not_null
          - unique
      - name: product_category_name
        tests:
          - not_null  

  - name: dim_geolocation
    description: "Geolocation dimension table for postal code, city, and state mapping."
    columns:
      - name: geolocation_zip_code_prefix
        tests:
          - not_null
          - unique
      - name: geolocation_city
        tests:
          - not_null
      - name: geolocation_state
        tests:
          - not_null    

  - name: fact_orders
    description: "Fact table for orders, joining order and payment data."
    columns:
      - name: order_id
        tests:
          - not_null
          - unique
      - name: customer_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_customer')
              field: customer_id
      - name: order_status
        tests:
          - not_null
          - accepted_values:
              values: ['delivered', 'canceled']
      - name: order_purchase_timestamp
        tests:
          - not_null    

  - name: fact_order_items
    description: "Fact table for order items at the granularity of each item in an order."
    columns:
      - name: order_id_item
        description: "Composite unique key (order_id + order_item_id)."
        tests:
          - not_null
          - unique
      - name: order_id
        tests:
          - not_null
          - relationships:
              to: ref('fact_orders')
              field: order_id
      - name: product_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_product')
              field: product_id
      - name: seller_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_seller')
              field: seller_id    